/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Question = IDL.Record({
  'correctIndex' : IDL.Nat,
  'text' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const Doubt = IDL.Record({
  'studentId' : IDL.Principal,
  'text' : IDL.Text,
  'isResolved' : IDL.Bool,
  'reply' : IDL.Opt(IDL.Text),
});
export const Feedback = IDL.Record({
  'studentId' : IDL.Principal,
  'text' : IDL.Text,
  'rating' : IDL.Nat,
});
export const Time = IDL.Int;
export const AttendanceRecord = IDL.Record({
  'isPresent' : IDL.Bool,
  'date' : Time,
});
export const Role = IDL.Variant({ 'teacher' : IDL.Null, 'student' : IDL.Null });
export const Profile = IDL.Record({ 'username' : IDL.Text, 'role' : Role });
export const Notification = IDL.Record({
  'userId' : IDL.Principal,
  'notificationType' : IDL.Text,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
});
export const Poll = IDL.Record({
  'question' : IDL.Text,
  'voteCounts' : IDL.Vec(IDL.Nat),
  'options' : IDL.Vec(IDL.Text),
});
export const Quiz = IDL.Record({
  'title' : IDL.Text,
  'questions' : IDL.Vec(Question),
});
export const Answer = IDL.Record({
  'questionIndex' : IDL.Nat,
  'selectedOption' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addNotification' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPoll' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [IDL.Nat], []),
  'createQuiz' : IDL.Func([IDL.Text, IDL.Vec(Question)], [IDL.Nat], []),
  'getAllDoubts' : IDL.Func([], [IDL.Vec(Doubt)], ['query']),
  'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getAttendanceHistory' : IDL.Func(
      [IDL.Opt(IDL.Principal)],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClassAttendance' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(AttendanceRecord)))],
      ['query'],
    ),
  'getGameLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Float64))],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getMyDoubts' : IDL.Func([], [IDL.Vec(Doubt)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPolls' : IDL.Func([], [IDL.Vec(Poll)], ['query']),
  'getQuizzes' : IDL.Func([], [IDL.Vec(Quiz)], ['query']),
  'getStudents' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'markDoubtResolved' : IDL.Func([IDL.Nat], [], []),
  'markNotificationsAsRead' : IDL.Func([], [], []),
  'registerUser' : IDL.Func([IDL.Text, Role], [], []),
  'replyDoubt' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'submitDoubt' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'submitFeedback' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
  'submitGameScore' : IDL.Func([IDL.Float64], [], []),
  'submitQuizAnswers' : IDL.Func([IDL.Nat, IDL.Vec(Answer)], [IDL.Int], []),
  'votePoll' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Question = IDL.Record({
    'correctIndex' : IDL.Nat,
    'text' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const Doubt = IDL.Record({
    'studentId' : IDL.Principal,
    'text' : IDL.Text,
    'isResolved' : IDL.Bool,
    'reply' : IDL.Opt(IDL.Text),
  });
  const Feedback = IDL.Record({
    'studentId' : IDL.Principal,
    'text' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const Time = IDL.Int;
  const AttendanceRecord = IDL.Record({
    'isPresent' : IDL.Bool,
    'date' : Time,
  });
  const Role = IDL.Variant({ 'teacher' : IDL.Null, 'student' : IDL.Null });
  const Profile = IDL.Record({ 'username' : IDL.Text, 'role' : Role });
  const Notification = IDL.Record({
    'userId' : IDL.Principal,
    'notificationType' : IDL.Text,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
  });
  const Poll = IDL.Record({
    'question' : IDL.Text,
    'voteCounts' : IDL.Vec(IDL.Nat),
    'options' : IDL.Vec(IDL.Text),
  });
  const Quiz = IDL.Record({
    'title' : IDL.Text,
    'questions' : IDL.Vec(Question),
  });
  const Answer = IDL.Record({
    'questionIndex' : IDL.Nat,
    'selectedOption' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addNotification' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPoll' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [IDL.Nat], []),
    'createQuiz' : IDL.Func([IDL.Text, IDL.Vec(Question)], [IDL.Nat], []),
    'getAllDoubts' : IDL.Func([], [IDL.Vec(Doubt)], ['query']),
    'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getAttendanceHistory' : IDL.Func(
        [IDL.Opt(IDL.Principal)],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClassAttendance' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(AttendanceRecord)))],
        ['query'],
      ),
    'getGameLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Float64))],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getMyDoubts' : IDL.Func([], [IDL.Vec(Doubt)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPolls' : IDL.Func([], [IDL.Vec(Poll)], ['query']),
    'getQuizzes' : IDL.Func([], [IDL.Vec(Quiz)], ['query']),
    'getStudents' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'markDoubtResolved' : IDL.Func([IDL.Nat], [], []),
    'markNotificationsAsRead' : IDL.Func([], [], []),
    'registerUser' : IDL.Func([IDL.Text, Role], [], []),
    'replyDoubt' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'submitDoubt' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'submitFeedback' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
    'submitGameScore' : IDL.Func([IDL.Float64], [], []),
    'submitQuizAnswers' : IDL.Func([IDL.Nat, IDL.Vec(Answer)], [IDL.Int], []),
    'votePoll' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };