/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Answer { 'questionIndex' : bigint, 'selectedOption' : bigint }
export interface AttendanceRecord { 'isPresent' : boolean, 'date' : Time }
export interface Doubt {
  'studentId' : Principal,
  'text' : string,
  'isResolved' : boolean,
  'reply' : [] | [string],
}
export interface Feedback {
  'studentId' : Principal,
  'text' : string,
  'rating' : bigint,
}
export interface Notification {
  'userId' : Principal,
  'notificationType' : string,
  'isRead' : boolean,
  'message' : string,
}
export interface Poll {
  'question' : string,
  'voteCounts' : Array<bigint>,
  'options' : Array<string>,
}
export interface Profile { 'username' : string, 'role' : Role }
export interface Question {
  'correctIndex' : bigint,
  'text' : string,
  'options' : Array<string>,
}
export interface Quiz { 'title' : string, 'questions' : Array<Question> }
export type Role = { 'teacher' : null } |
  { 'student' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addNotification' : ActorMethod<[Principal, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPoll' : ActorMethod<[string, Array<string>], bigint>,
  'createQuiz' : ActorMethod<[string, Array<Question>], bigint>,
  'getAllDoubts' : ActorMethod<[], Array<Doubt>>,
  'getAllFeedback' : ActorMethod<[], Array<Feedback>>,
  'getAttendanceHistory' : ActorMethod<
    [[] | [Principal]],
    Array<AttendanceRecord>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClassAttendance' : ActorMethod<
    [],
    Array<[Principal, Array<AttendanceRecord>]>
  >,
  'getGameLeaderboard' : ActorMethod<[], Array<[Principal, number]>>,
  'getLeaderboard' : ActorMethod<[], Array<Profile>>,
  'getMyDoubts' : ActorMethod<[], Array<Doubt>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPolls' : ActorMethod<[], Array<Poll>>,
  'getQuizzes' : ActorMethod<[], Array<Quiz>>,
  'getStudents' : ActorMethod<[], Array<Profile>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAttendance' : ActorMethod<[Principal, boolean], undefined>,
  'markDoubtResolved' : ActorMethod<[bigint], undefined>,
  'markNotificationsAsRead' : ActorMethod<[], undefined>,
  'registerUser' : ActorMethod<[string, Role], undefined>,
  'replyDoubt' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'submitDoubt' : ActorMethod<[string], bigint>,
  'submitFeedback' : ActorMethod<[string, bigint], bigint>,
  'submitGameScore' : ActorMethod<[number], undefined>,
  'submitQuizAnswers' : ActorMethod<[bigint, Array<Answer>], bigint>,
  'votePoll' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];