/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Doubt {
    studentId: Principal;
    text: string;
    isResolved: boolean;
    reply?: string;
}
export type Time = bigint;
export interface Notification {
    userId: Principal;
    notificationType: string;
    isRead: boolean;
    message: string;
}
export interface Feedback {
    studentId: Principal;
    text: string;
    rating: bigint;
}
export interface Quiz {
    title: string;
    questions: Array<Question>;
}
export interface Answer {
    questionIndex: bigint;
    selectedOption: bigint;
}
export interface Question {
    correctIndex: bigint;
    text: string;
    options: Array<string>;
}
export interface Profile {
    username: string;
    role: Role;
}
export interface Poll {
    question: string;
    voteCounts: Array<bigint>;
    options: Array<string>;
}
export interface AttendanceRecord {
    isPresent: boolean;
    date: Time;
}
export enum Role {
    teacher = "teacher",
    student = "student"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addNotification(userId: Principal, message: string, notificationType: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPoll(question: string, options: Array<string>): Promise<bigint>;
    createQuiz(title: string, questions: Array<Question>): Promise<bigint>;
    getAllDoubts(): Promise<Array<Doubt>>;
    getAllFeedback(): Promise<Array<Feedback>>;
    getAttendanceHistory(studentId: Principal | null): Promise<Array<AttendanceRecord>>;
    getCallerUserProfile(): Promise<Profile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClassAttendance(): Promise<Array<[Principal, Array<AttendanceRecord>]>>;
    getGameLeaderboard(): Promise<Array<[Principal, number]>>;
    getLeaderboard(): Promise<Array<Profile>>;
    getMyDoubts(): Promise<Array<Doubt>>;
    getNotifications(): Promise<Array<Notification>>;
    getPolls(): Promise<Array<Poll>>;
    getQuizzes(): Promise<Array<Quiz>>;
    getStudents(): Promise<Array<Profile>>;
    getUserProfile(userId: Principal): Promise<Profile | null>;
    isCallerAdmin(): Promise<boolean>;
    markAttendance(studentId: Principal, isPresent: boolean): Promise<void>;
    markDoubtResolved(doubtId: bigint): Promise<void>;
    markNotificationsAsRead(): Promise<void>;
    registerUser(username: string, role: Role): Promise<void>;
    replyDoubt(doubtId: bigint, reply: string): Promise<void>;
    saveCallerUserProfile(profile: Profile): Promise<void>;
    submitDoubt(text: string): Promise<bigint>;
    submitFeedback(text: string, rating: bigint): Promise<bigint>;
    submitGameScore(points: number): Promise<void>;
    submitQuizAnswers(quizId: bigint, answers: Array<Answer>): Promise<bigint>;
    votePoll(pollId: bigint, optionIndex: bigint): Promise<void>;
}
import type { Doubt as _Doubt, Profile as _Profile, Role as _Role, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addNotification(arg0: Principal, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNotification(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNotification(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPoll(arg0: string, arg1: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPoll(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPoll(arg0, arg1);
            return result;
        }
    }
    async createQuiz(arg0: string, arg1: Array<Question>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuiz(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuiz(arg0, arg1);
            return result;
        }
    }
    async getAllDoubts(): Promise<Array<Doubt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDoubts();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDoubts();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFeedback(): Promise<Array<Feedback>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFeedback();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFeedback();
            return result;
        }
    }
    async getAttendanceHistory(arg0: Principal | null): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceHistory(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceHistory(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClassAttendance(): Promise<Array<[Principal, Array<AttendanceRecord>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClassAttendance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClassAttendance();
            return result;
        }
    }
    async getGameLeaderboard(): Promise<Array<[Principal, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGameLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGameLeaderboard();
            return result;
        }
    }
    async getLeaderboard(): Promise<Array<Profile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyDoubts(): Promise<Array<Doubt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDoubts();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDoubts();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return result;
        }
    }
    async getPolls(): Promise<Array<Poll>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPolls();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPolls();
            return result;
        }
    }
    async getQuizzes(): Promise<Array<Quiz>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizzes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizzes();
            return result;
        }
    }
    async getStudents(): Promise<Array<Profile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudents();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudents();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markAttendance(arg0: Principal, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAttendance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAttendance(arg0, arg1);
            return result;
        }
    }
    async markDoubtResolved(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markDoubtResolved(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markDoubtResolved(arg0);
            return result;
        }
    }
    async markNotificationsAsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationsAsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationsAsRead();
            return result;
        }
    }
    async registerUser(arg0: string, arg1: Role): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, to_candid_Role_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, to_candid_Role_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async replyDoubt(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.replyDoubt(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.replyDoubt(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: Profile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_Profile_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_Profile_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitDoubt(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDoubt(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDoubt(arg0);
            return result;
        }
    }
    async submitFeedback(arg0: string, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFeedback(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFeedback(arg0, arg1);
            return result;
        }
    }
    async submitGameScore(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitGameScore(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitGameScore(arg0);
            return result;
        }
    }
    async submitQuizAnswers(arg0: bigint, arg1: Array<Answer>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuizAnswers(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuizAnswers(arg0, arg1);
            return result;
        }
    }
    async votePoll(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.votePoll(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.votePoll(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Doubt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Doubt): Doubt {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Profile_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : from_candid_Profile_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    role: _Role;
}): {
    username: string;
    role: Role;
} {
    return {
        username: value.username,
        role: from_candid_Role_n11(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId: Principal;
    text: string;
    isResolved: boolean;
    reply: [] | [string];
}): {
    studentId: Principal;
    text: string;
    isResolved: boolean;
    reply?: string;
} {
    return {
        studentId: value.studentId,
        text: value.text,
        isResolved: value.isResolved,
        reply: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.reply))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    teacher: null;
} | {
    student: null;
}): Role {
    return "teacher" in value ? Role.teacher : "student" in value ? Role.student : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Profile>): Array<Profile> {
    return value.map((x)=>from_candid_Profile_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Doubt>): Array<Doubt> {
    return value.map((x)=>from_candid_Doubt_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Profile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Profile): _Profile {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    role: Role;
}): {
    username: string;
    role: _Role;
} {
    return {
        username: value.username,
        role: to_candid_Role_n16(_uploadFile, _downloadFile, value.role)
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    teacher: null;
} | {
    student: null;
} {
    return value == Role.teacher ? {
        teacher: null
    } : value == Role.student ? {
        student: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
